---
- name: Ensure Python, pip and required Python Kubernetes, DB's and DevOps dependencies are installed 
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-kubernetes
      - python3-yaml
      - python3-openshift
      - python3-jsonpatch
      - python3-passlib
      - python3-venv
      - python3-requests
      - python3-psycopg2
      - python3-redis
      - python3-docker
    state: present
    update_cache: yes